__copyright__ = 'Copyright (C) 2019 Yusuke Oya'
__version__ = '0.1.0'
__license__ = 'MIT'
__author__ = 'Yusuke Oya'
__author_email__ = 'curio@antique-cafe.net'
__url__ = 'http://antique-cafe.net'
